### ISSUE TITLE
Windows11 Build Error 

### ISSUE THREAD

**Issue by au-top** [ryanheise/just_audio#838]
**Which API doesn't behave as documented, and how does it misbehave?**
Windows Build Fail 
**Minimal reproduction project**

`pubspec.yaml`

```yaml
name: test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-79.0.dev <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.29
  just_audio_windows: any
  just_audio_mpv: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


```

**To Reproduce (i.e. user steps, not code)**

**Error messages**
main error info
```
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(471,14): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(486,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(623,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(757,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(894,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(1149,55): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(1178,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(1517,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(1654,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(1820,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(2199,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(2318,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(2423,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(2935,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(3060,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(3418,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(3673,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(5349,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(5633,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(5769,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(5986,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(6108,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(6235,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(6400,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(6876,14): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(6907,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(7149,24): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(7151,26): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[   +1 ms]   D:\Windows Kits\10\Include\10.0.22621.0\um\ocidl.h(7164,55): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]   D:\Windows Kits\10\Include\10.0.22621.0\shared\dxgi.h(323,5): error C2872: ��IUnknown��: ����ȷ�ķ��� [D:\project\flutterProject\free_message\build\windows\plugins\just_audio_windows\just_audio_windows_plugin.vcxproj]
[        ]     0 ������
[        ]     30 ������
[        ] ����ʱ�� 00:00:21.99
[  +30 ms] Building Windows application... (completed in 32.3s)
[+1836 ms] Exception: Build process failed.
[   +5 ms] "flutter run" took 37,014ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:714:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1244:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows11
```
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎9/‎26
操作系统版本	22621.521
体验	Windows Feature Experience Pack 1000.22634.1000.0
```

**Flutter SDK version**
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel master, 3.4.0-34.0.pre.8, on Microsoft Windows [版本 10.0.22621.521], locale zh-CN)
    • Flutter version 3.4.0-34.0.pre.8 on channel master at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c522996be (9 days ago), 2022-09-29 13:04:19 +0800
    • Engine revision c003042e52
    • Dart version 2.19.0 (build 2.19.0-252.0.dev)
    • DevTools version 2.17.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at D:\VSSDK\IDE
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.72.0)
    • VS Code at C:\Users\autop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.51.20221003

[√] VS Code (version 1.73.0-insider)
    • VS Code at C:\Users\autop\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • OW20W2 (mobile)   • 9e530c37 • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22621.521]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 106.0.1370.34

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Additional context**
